apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
      podTemplate: clickhouse:22.9-alpine
  configuration:
    users:
      admin/password: test23
      clickhouse_operator/password: test23
      default/password: ""
      default/networks/ip: "::/0"
      dev/networks/ip: "::/0"
      dev/password: test23
      dev/profile: default
    clusters:
      - name: "ch"
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: log-volume-template
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    podTemplates:
      - name: clickhouse:22.9-alpine
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.9-alpine
