apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
generatorOptions:
  disableNameSuffixHash: true
resources:
  - configmap.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
