apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-postgres
  labels:
    app: mlflow-postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
  storageClassName: standard
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mlflow-postgres
