apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio
spec:
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      volumes:
      - name: data-minio-mlflow
        persistentVolumeClaim:
          claimName: mlflow-pvc
      containers:
      - name: mlflow-minio
        image: minio/minio:latest
        args: [
          "server",
          "/data",
        ]
        volumeMounts:
        - name: data-minio-mlflow
          mountPath: '/data'
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        - name: MINIO_CONSOLE_ADDRESS
          value: ":9090"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://127.0.0.1:9090"
        ports:
        - containerPort: 9000
        - containerPort: 9090
