apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: https
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: mlflow-minio
